#!/bin/bash
set -e

# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section

if ! [ -a /etc/openisr/hostid ]; then

	dd if=/dev/urandom bs=4 count=1 | od -An -t d4 | tr -d " -" > /etc/openisr/hostid 2> /dev/null

fi

echo "For a good time, run:";
echo "  sudo module-assistant auto-install openisr";

# seems to have a problem with dpkg's status db lock.. will investigate
#/usr/bin/module-assistant auto-install openisr;

