Document: openisr
Title: Debian openisr Manual
Author: <insert document author here>
Abstract: This manual describes what openisr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openisr/openisr.sgml.gz

Format: postscript
Files: /usr/share/doc/openisr/openisr.ps.gz

Format: text
Files: /usr/share/doc/openisr/openisr.text.gz

Format: HTML
Index: /usr/share/doc/openisr/html/index.html
Files: /usr/share/doc/openisr/html/*.html

  
