#!/bin/bash

#
# $Id: mklev1,v 1.1 2004/11/01 16:18:53 makozuch Exp $
#

VERSION=1

CHUNKSIZE_KB=128
CHUNKSPERDIR=512

MAXNUMDIRS=512

CHUNKSIZE=$(( $CHUNKSIZE_KB * 1024 ))

# Check the number of arguments
if [[ $# -ne 2 ]]; then
    echo "usage: $0 <dest-dir> <size> [kmg]"
    exit
fi

DEST=$1
TMPVOLSIZE=`./kmg $2`
basefile_temp=`mktemp -q mklev.XXXXXXXX`
basefile=`mktemp -q mklev.XXXXXXXX`

# Calculate num files
NUMCHUNKS=`echo "$TMPVOLSIZE $CHUNKSIZE / p" | dc`
NUMCHUNKS_REM=`echo "$TMPVOLSIZE $CHUNKSIZE % p" | dc`
if [[ $NUMCHUNKS_REM -ne 0 ]]; then
    (( NUMCHUNKS += 1))
fi
NUMDIRS=`echo "$NUMCHUNKS $CHUNKSPERDIR / p" | dc`
NUMDIRS_REM=`echo "$NUMCHUNKS $CHUNKSPERDIR % p" | dc`
if [[ $NUMDIRS_REM -ne 0 ]]; then
    (( NUMDIRS += 1))
fi

VOLSIZE=`echo "$NUMCHUNKS $CHUNKSIZE * p" | dc`

# Check num dirs
if [[ $NUMDIRS -gt $MAXNUMDIRS ]]; then
    echo "ERROR: num directories (${NUMDIRS}) greater than limit (${MAXNUMDIRS})."
    exit
fi

# Make destination directory
if [[ -e $DEST ]]; then
	echo "ERROR: Directory $DEST already exists."
	exit
else
	mkdir $DEST
	rm -f $basefile;touch $basefile
	dd bs=1024 count=${CHUNKSIZE_KB} if=/dev/zero of=$basefile_temp # >> /dev/null 2>&1
	touch $DEST/keyring
	./processchunk $basefile_temp $basefile $DEST/keyring
	keystring=`cat $DEST/keyring`
	for (( i=1 ; i < $NUMCHUNKS ; i++ )); do
		echo $keystring >> $DEST/keyring
	done
fi

# Make index file
INDEXFILE=index.lev1
echo "VERSION= ${VERSION}" > ${DEST}/${INDEXFILE}
echo "CHUNKSIZE= ${CHUNKSIZE}" >> ${DEST}/${INDEXFILE}
echo "CHUNKSPERDIR= ${CHUNKSPERDIR}" >> ${DEST}/${INDEXFILE}
echo "VOLSIZE= ${VOLSIZE}" >> ${DEST}/${INDEXFILE}
echo "NUMCHUNKS= ${NUMCHUNKS}" >> ${DEST}/${INDEXFILE}
echo "NUMDIRS= ${NUMDIRS}" >> ${DEST}/${INDEXFILE}

# Create files and directories
for (( CHUNK=0 ; CHUNK<NUMCHUNKS ; CHUNK++ )) ; do
    CHUNKNAME=$( printf "%04d" $( echo "$CHUNK $CHUNKSPERDIR % p" | dc ) )
    DIRNAME=${DEST}/$( printf "%04d" $( echo "$CHUNK $CHUNKSPERDIR / p" | dc ) )

    if [[ ! -e $DIRNAME ]]; then
	echo "Making directory $DIRNAME ..."
	mkdir $DIRNAME
    fi

    #echo "     ${DIRNAME}/${CHUNKNAME}"
    #dd if=/dev/zero of=${DIRNAME}/${CHUNKNAME} bs=1024 count=${CHUNKSIZE_KB} >> /dev/null 2>&1
	 cp $basefile ${DIRNAME}/${CHUNKNAME}
done
rm -f $basefile $basefile_temp
